// action types
export const INIT_API_REQUEST = "INIT_API_REQUEST"
export const INIT_API_REQUEST_SUCCESS = "INIT_API_REQUEST_SUCCESS"
export const INIT_API_REQUEST_FAILURE = "INIT_API_REQUEST_FAILURE"

export const CHANGE_ACTIVE_VIEW = "CHANGE_ACTIVE_VIEW"
export const CHANGE_ACTIVE_VIEW_SUCCESS = "CHANGE_ACTIVE_VIEW_SUCCESS"

export const FETCH_PLAYER = "FETCH_PLAYER"
export const FETCH_PLAYER_SUCCESS = "FETCH_PLAYER_SUCCESS"
export const FETCH_PLAYER_FAILURE = "FETCH_PLAYER_FAILURE"