// action types
export const INIT_API_REQUEST = "INIT_API_REQUEST"
export const INIT_API_REQUEST_SUCCESS = "INIT_API_REQUEST_SUCCESS"
export const INIT_API_REQUEST_FAILURE = "INIT_API_REQUEST_FAILURE"

export const CHANGE_ACTIVE_VIEW = "CHANGE_ACTIVE_VIEW"
export const CHANGE_ACTIVE_VIEW_SUCCESS = "CHANGE_ACTIVE_VIEW_SUCCESS"