export const HOME_PAGE = "HOME_PAGE";
export const PLAYERS_PAGE = "PLAYERS_PAGE";
export const PLAYER_PAGE_SINGLE = "PLAYER_PAGE_SINGLE";
export const TEAMS_PAGE = "TEAMS_PAGE";
export const TEAM_PAGE_SINGLE = "TEAM_PAGE_SINGLE";
